### ISSUE TITLE
Docker container has Tailscale version “1.72.1-ERR-BuildInfo”

### ISSUE THREAD

**Issue by avidrissman** [tailscale/golink#140]
I use the docker container `ghcr.io/tailscale/golink:main` and I just updated to the latest version. When I go to my Tailscale Admin page, I see that the Tailscale version is listed as “1.72.1-ERR-BuildInfo”.

That doesn’t strike me as a useful version number and it seems like something is broken in the release pipeline; can you fix it?

**Comment by willnorris** [comment]
hmm, this does seem to be a newer behavior.  I see it as well in my homelab with the latest container image.  Previously, we had version numbers similar to `1.62.1-dev20240412`.  

Relevant code for these strings is https://github.com/tailscale/tailscale/blob/aeb15dea3032c0560793190731dd6a06b45850b2/version/version.go#L86-L102

@awly have you seen this with other tsnet apps?  I doubt it would have had anything to do with #137, since we didn't actually change how we build the golink binary itself.

**Comment by patrickod** [comment]
I don't think this behavior is golink specific, or at least I have observed the same `-ERR-BuildInfo` suffixes in personal software that uses `tailscale.com/tsnet`
